#! /bin/sh
### BEGIN INIT INFO
# Provides:          control-daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control server
# Description: Control server to send command to the drone
### END INIT INFO

NAME=navio-control
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
USER=root
OPTS=""

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile \
      --user $USER --chuid $USER --startas $DAEMON -- $OPTS
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping system $NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm -f $PIDFILE
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    config)
        ;;

    status)
        status_of_proc "$NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
